version: "3.8"

services:
  app:
    build: .
    image: xq/covid_info
    # command: flask run -h 0.0.0.0 -p 3000
    command: gunicorn -b :3000 covid_info.app:app
    environment:
      FLASK_DEBUG: 0
      FLASK_APP: covid_info.app
      DEVELOPER_KEY: N8YMmumHskmhrFmnxP29OAkERGzkmBtk
      WEB_KEY: Y6jpl8OGLbQcbg67zGzrGsqYdS6bTiKr
      ADDR_TO_LOC_URL: https://api.map.baidu.com/geocoding/v3/?

    volumes:
      - .:/code
    ports:
      - 3000:3000

networks:
  default:
    name: covid_info
